# Generated by Django 5.1.6 on 2025-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0005_alter_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
