# Generated by Django 5.1.6 on 2025-04-23 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0007_alter_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
